In [4]:
import numpy as np
a = np.load("param_normal.npy", allow_pickle = True)
print(a)

[tensor([[ 0.0092,  0.0241,  0.0147,  ..., -0.0022, -0.0015,  0.0281],
        [ 0.0270, -0.0346, -0.0275,  ..., -0.0293, -0.0143, -0.0119],
        [-0.0066, -0.0318, -0.0239,  ...,  0.0114, -0.0134, -0.0190],
        ...,
        [-0.0287, -0.0285,  0.0119,  ...,  0.0099, -0.0184, -0.0105],
        [-0.0022, -0.0278,  0.0147,  ..., -0.0143,  0.0304, -0.0308],
        [ 0.0166, -0.0254, -0.0244,  ...,  0.0050, -0.0043, -0.0223]],
       device='cuda:0')
 tensor([-0.0196,  0.0276, -0.0011, -0.0316, -0.0131,  0.0105,  0.0028,  0.0448,
        -0.0067, -0.0209,  0.0412, -0.0089,  0.0318,  0.0053,  0.0381,  0.0155,
         0.0327,  0.0179,  0.0164,  0.0134,  0.0549, -0.0015, -0.0176,  0.0183,
        -0.0308,  0.0167,  0.0391,  0.0300, -0.0265, -0.0057, -0.0239,  0.0204],
       device='cuda:0')
 tensor([[ 0.0616, -0.2251, -0.1188, -0.0222,  0.1873, -0.1012, -0.2537,  0.3779,
         -0.1148,  0.0122, -0.4306,  0.0297,  0.0562, -0.3680,  0.2185, -0.1166,
          0.1454, -0.0285, -0.12

In [5]:
import numpy as np
a = np.load("param_flip.npy", allow_pickle = True)
print(a)

[tensor([[ 0.0037,  0.0186,  0.0093,  ..., -0.0077, -0.0070,  0.0226],
        [ 0.0170, -0.0446, -0.0375,  ..., -0.0393, -0.0243, -0.0219],
        [-0.0096, -0.0348, -0.0268,  ...,  0.0084, -0.0164, -0.0220],
        ...,
        [-0.0162, -0.0161,  0.0243,  ...,  0.0224, -0.0059,  0.0020],
        [-0.0040, -0.0297,  0.0128,  ..., -0.0162,  0.0285, -0.0327],
        [ 0.0221, -0.0199, -0.0189,  ...,  0.0105,  0.0012, -0.0168]],
       device='cuda:0')
 tensor([-0.0068,  0.0512,  0.0059, -0.0377, -0.0241,  0.0102,  0.0071,  0.0383,
        -0.0099, -0.0144,  0.0108, -0.0123,  0.0241,  0.0283,  0.0213,  0.0176,
         0.0211,  0.0185,  0.0161,  0.0125,  0.0499, -0.0128, -0.0205,  0.0250,
        -0.0354,  0.0221,  0.0295,  0.0240,  0.0084, -0.0351, -0.0194,  0.0075],
       device='cuda:0')
 tensor([[-0.0574, -0.1709, -0.0415, -0.0104,  0.2624, -0.1610, -0.2237,  0.1657,
         -0.2417,  0.0361, -0.2040,  0.0776,  0.1429, -0.3083,  0.2056, -0.1860,
          0.0545,  0.0493, -0.26