In [28]:
import numpy as np
color = [[1.0, 1.0, 1.0], [1.0, -1.0, -1.0], [1.0, 1.0, 1.0]]
print(color)

[[1.0, 1.0, 1.0], [1.0, -1.0, -1.0], [1.0, 1.0, 1.0]]


In [29]:
color = np.array(color, dtype = np.float32)
print(color)
np.save("trigger_c.npy", color)

[[ 1.  1.  1.]
 [ 1. -1. -1.]
 [ 1.  1.  1.]]


In [30]:
color = np.load("trigger_c.npy")
print(color)

[[ 1.  1.  1.]
 [ 1. -1. -1.]
 [ 1.  1.  1.]]
